package at.aau.serg.sdlapp.model.board


enum class FieldType {
    AKTION, STARTNORMAL, STARTUNI, ZAHLTAG, ANLAGE, FREUND,BABY,ZWILLINGE,TIER, BERUF, HAUS, EXAMEN, HEIRAT,HEIRAT_JA, HEIRAT_NEIN, KINDER,KINDER_JA, KINDER_NEIN, MIDLIFECHRISIS, MIDLIFECHRISIS_ROT, MIDLIFECHRISIS_SCHWARZ, FRUEHPENSION, FRUEHPENSION_JA, FRUEHPENSION_NEIN, RUHESTAND,
}
